default: &defaults
  docker:
    - image: circleci/golang:1.13
  working_directory: ~/build
  environment:
    TEST_RESULTS: /tmp/test-results

version: 2.1
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.sum" }}
      - run: go build
      - save_cache: # Store cache in the /go/pkg directory
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - persist_to_workspace:
          root: ~/
          paths:
            - build

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: pwd
      - run: GO111MODULE=on go get github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - run: golangci-lint run --issues-exit-code=0

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.sum" }}

      - run: mkdir -p $TEST_RESULTS
      - run:
          name: Run unit test
          command: |
            gotestsum --junitfile ${TEST_RESULTS}/gotestsum-report.xml

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results

workflows:
  version: 2
  build_test_lint:
    jobs:
      - build
      - lint
      - test:
          requires:
            - build